name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:            # Job seviyesinde de ekliyoruz
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v1.6.0  # v1 yerine güncel sürüm
        with:
          workload_identity_provider: "projects/212643517584/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-deploy@pure-highlander-471707-t2.iam.gserviceaccount.com"

      - name: Build & Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/pure-highlander-471707-t2/socialmedia-backend
