name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Test Backend GCP auth
  test-backend-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Authenticate to GCP (Backend) via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_BACKEND }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Test gcloud access (Backend)
        run: |
          echo "Listing GCP projects to test auth..."
          gcloud projects list

  # Deploy Backend
  deploy-backend:
    runs-on: ubuntu-latest
    needs: test-backend-auth
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Authenticate to GCP (Backend) via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_BACKEND }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build & Push Backend Docker image
        run: |
          cd backend
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-backend

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy socialmedia-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-backend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --add-cloudsql-instances ${{ secrets.CLOUDSQL_INSTANCE }} \
            --set-env-vars DATABASE_HOST=/cloudsql/${{ secrets.CLOUDSQL_INSTANCE }},DATABASE_USER=${{ secrets.DB_USER }},DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }},DATABASE_NAME=${{ secrets.DB_NAME }}
