name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_BACKEND }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy social-media-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/backend-image:latest \
            --region europe-west1 \
            --platform managed
